# 错误截获

## try...catch

```js
(function() {
    try {
        //try执行的语句如果抛出错误则执行catch
        throw new Error();
    } catch(x) {
        //catch的参数x是错误描述
        var x=1, y=2;//这里将x变成数字
        console.log(x);//1
    }
    //try catch语句块与其他内容都在同一个作用域下
    console.log(x);//undefined
    console.log(y);// 2
})()
```